eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.apache.http.wire=: DEBUG
