eureka:
  instance:
    hostname: registry
  client:
    service-url:
      default-zone: http://registry:8761/eureka
    register-with-eureka: true
    fetch-registry: false

spring:
  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.apache.http.wire: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
