spring:
  cloud:
    gateway:
      routes:
        messaging:
          path: /message/**
          serviceId: sender-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service_discovery/eureka/
  instance:
    hostname: localhost
