spring:
  cloud:
    gateway:
      routes:
        messaging:
          path: /message/**
          serviceId: sender-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://service_discovery/eureka/
