eureka:
  instance:
    hostname: registry
    nonSecurePort: 8761
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/eureka
    register-with-eureka: true
    fetch-registry: false

spring:
  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.apache.http.wire: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
